In [76]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [77]:
data=pd.read_csv(r"D:\customer_churn_project\data\churn.csv")

In [78]:
data=data.drop(columns="customerID")

In [79]:
data.head(3)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes

In [80]:
data["TotalCharges"]=pd.to_numeric(data["TotalCharges"],errors="coerce")

In [81]:
data["TotalCharges"] = data["TotalCharges"].fillna(0)

In [82]:
data["Churn"] = data["Churn"].map({"No": 0, "Yes": 1})

In [83]:
binary_cols = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
               'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
               'StreamingTV', 'StreamingMovies', 'PaperlessBilling']

In [84]:
for col in binary_cols:
    if col == 'gender':
        data[col] = data[col].map({"Female": 0, "Male": 1})
    elif col == 'MultipleLines':
        data[col] = data[col].map({"No": 0, "No phone service": 0, "Yes": 1})
    else:
        data[col] = data[col].map({"No": 0, "No internet service": 0, "Yes": 1})

In [85]:
print(data['MultipleLines'].value_counts())

MultipleLines
0    4072
1    2971
Name: count, dtype: int64

In [86]:
data.to_csv(r"D:\customer_churn_project\data\churn_cleaned.csv", index=False)
print("✅ Cleaned data saved with correct preprocessing order")

✅ Cleaned data saved with correct preprocessing order

In [87]:
data.head(3)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,DSL,0,1,0,0,0,0,Month-to-month,1,Electronic check,29.85,29.85,0
1,1,0,0,0,34,1,0,DSL,1,0,1,0,0,0,One year,0,Mailed check,56.95,1889.50,0
2,1,0,0,0,2,1,0,DSL,1,1,0,0,0,0,Month-to-month,1,Mailed check,53.85,108.15,1